/*
 * ForgotPassword class holds the UI of the Login Panel
 */
package back_end;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;

/**
 * @author Francisco Jose Bejarano Escano
 * EC1825088
 * @date 23/03/2022
 * @location Edinburgh
 * @version 1.0
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbForgotPasswordTitle = new javax.swing.JLabel();
        lbNewPass = new javax.swing.JLabel();
        lbConfPass = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lbUsernameFP = new javax.swing.JLabel();
        txtUsernameFP = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtNewPass = new javax.swing.JPasswordField();
        txtConfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Webflix - Forgot Password");
        setIconImage(new ImageIcon(getClass().getResource("/images/favicon.png")).getImage());
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbForgotPasswordTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbForgotPasswordTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbForgotPasswordTitle.setText("Forgot Password?");

        lbNewPass.setText("New Password: ");

        lbConfPass.setText("Confirm Password: ");

        btnChange.setText("Change Password");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lbUsernameFP.setText("Username:");

        btnBack.setText("Back to Login");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtConfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfPassKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConfPass)
                    .addComponent(lbNewPass)
                    .addComponent(lbUsernameFP)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsernameFP)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnChange)
                                .addGap(18, 18, 18)
                                .addComponent(btnExit))
                            .addComponent(txtNewPass))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtConfPass))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbForgotPasswordTitle)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lbForgotPasswordTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsernameFP)
                    .addComponent(txtUsernameFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewPass)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConfPass)
                    .addComponent(txtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChange)
                    .addComponent(btnExit)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        changePassword();

    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        // Display a warning panel
        int exitBtn = JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
            JOptionPane.YES_NO_OPTION);

        // Exit the app with the chosen option
        if(exitBtn == JOptionPane.YES_OPTION) {

            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        setVisible(false); // The forgot password panel dissappear
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtConfPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfPassKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    
            changePassword();
            txtConfPass.transferFocus();
        }
    }//GEN-LAST:event_txtConfPassKeyReleased

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ForgotPassword().setVisible(true);
        });
        
    }
    
    public void changePassword() {
            
        try {
            
            // Instance of the ConnectMySQL class
            ConnectMySQL Con = new ConnectMySQL();
            // Get the text from a textfield of the UI
            String u = txtUsernameFP.getText();
            String np = txtNewPass.getText();
            String cp = txtConfPass.getText();
             
            // Check if both passwords are equals
            if(np.equals(cp)) {                           
            
                // Connects with the database
                Con.ConnectDatabase();

                // Send a query to the database to retrieve information
                String SQL = "SELECT * FROM administrator WHERE username = '" +u +"'";

                // Executes the given SQL statement, which returns a single ResultSet object
                Con.result = Con.statement.executeQuery(SQL);

                // If the query finds a row with the given information from the textfields
                if(Con.result.next()) {
                    
                    // Updates the password of the user
                    SQL = "UPDATE `administrator` SET `password` = ? WHERE `username` = ?";
                    
                    try(Connection conn = Con.connection; 
                        PreparedStatement preparedStmt = conn.prepareStatement(SQL)) {
                        
                            preparedStmt.setString(1, np);
                            preparedStmt.setString(2, u);

                            preparedStmt.executeUpdate();
                    }
                    catch(SQLException ex) {
                        
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }

                    Object [] options = {"OK",
                                         "Back to Login"};
                    
                    int choosen = JOptionPane.showOptionDialog(jPanel1,//parent container of JOptionPane
                        "Password changed successfuly",
                        "Change Password",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,//do not use a custom Icon
                        options,//the titles of buttons
                        options[1]);//default button title
                    
                    if(choosen == 1) {
                        
                        setVisible(false); // The forgot password panel dissappear
                        
                    }
                    
                }
                else {

                    JOptionPane.showMessageDialog(null, "Username not found.\nPlease insert a valid username");
                }
            }
            else{
                
                 JOptionPane.showMessageDialog(null, "Passwords are different");
            }
        }   
        catch (SQLException ex) {
            Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbConfPass;
    private javax.swing.JLabel lbForgotPasswordTitle;
    private javax.swing.JLabel lbNewPass;
    private javax.swing.JLabel lbUsernameFP;
    private javax.swing.JPasswordField txtConfPass;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JTextField txtUsernameFP;
    // End of variables declaration//GEN-END:variables
}
